tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
  - command: curl -fsSL https://deno.land/x/install/install.sh | sh && export DENO_INSTALL="/home/gitpod/.deno" && export PATH="$DENO_INSTALL/bin:$PATH"

vscode:
  extensions:
    - ms-azuretools.vscode-docker
